// foo.ebnf - test EBNF file
Production  = name "=" Expression "." .
Expression  = Alternative { "|" Alternative } .
Alternative = Term { Term } .
Term        = name | token [ "..." token ] | Group | Option | Repetition .
Group       = "(" Expression ")" .
Option      = "[" Expression "]" .
Repetition  = "{" Expression "}" .
letter      = "a"..."z" | "A"..."Z" .
name        = letter {letter} .
token       = "\"" ("\x00"..."\xFF" | "\\x" hex hex | "\\" oct oct oct) "\"" .
hex         = "0"..."9" | "A"..."F" | "a"..."f" .
oct         = "0"..."7" .
